#!/usr/bin/env python3
"""Enumerate finite actions generated by a permutation q and a commuting map t.

For each n this computes:
  A[n] = isomorphism classes of all pairs (q,t), q invertible and qt=tq;
  C[n] = connected isomorphism classes.

The orbit count for fixed q uses Burnside over the centralizer of q.  If a
centralizer element g fixes t, then t is an endomorphism of the finite
<q,g>-set.  The number of such endomorphisms is computed orbit-by-orbit.
"""

from fractions import Fraction
from itertools import permutations, product
from math import factorial
import argparse


def partitions(n, cap=None):
    if n == 0:
        yield ()
        return
    if cap is None or cap > n:
        cap = n
    for first in range(cap, 0, -1):
        for rest in partitions(n - first, first):
            yield (first,) + rest


def canonical_permutation(parts):
    q = []
    cycles = []
    start = 0
    for length in parts:
        cyc = list(range(start, start + length))
        cycles.append(cyc)
        start += length
    q = list(range(start))
    for cyc in cycles:
        for i, x in enumerate(cyc):
            q[x] = cyc[(i + 1) % len(cyc)]
    return tuple(q), cycles


def centralizer_elements(cycles, n):
    by_length = {}
    for cyc in cycles:
        by_length.setdefault(len(cyc), []).append(cyc)

    blocks = []
    for length, same_cycles in sorted(by_length.items()):
        block = []
        count = len(same_cycles)
        for sigma in permutations(range(count)):
            for rotations in product(range(length), repeat=count):
                partial = {}
                for i, source in enumerate(same_cycles):
                    target = same_cycles[sigma[i]]
                    shift = rotations[i]
                    for pos, x in enumerate(source):
                        partial[x] = target[(pos + shift) % length]
                block.append(partial)
        blocks.append(block)

    for choices in product(*blocks):
        g = list(range(n))
        for partial in choices:
            for x, y in partial.items():
                g[x] = y
        yield tuple(g)


def compose(a, b):
    """a after b."""
    return tuple(a[b[x]] for x in range(len(a)))


def inverse(a):
    out = [0] * len(a)
    for x, y in enumerate(a):
        out[y] = x
    return tuple(out)


def generated_group(q, g):
    n = len(q)
    identity = tuple(range(n))
    gens = (q, inverse(q), g, inverse(g))
    seen = {identity}
    frontier = [identity]
    while frontier:
        h = frontier.pop()
        for a in gens:
            ah = compose(a, h)
            if ah not in seen:
                seen.add(ah)
                frontier.append(ah)
    return tuple(seen)


def equivariant_endomorphism_count(q, g):
    """Number of maps t commuting with both q and g."""
    n = len(q)
    group = generated_group(q, g)
    unseen = set(range(n))
    answer = 1
    while unseen:
        x = min(unseen)
        orbit = {h[x] for h in group}
        unseen.difference_update(orbit)
        stabilizer = [h for h in group if h[x] == x]
        fixed_points = sum(
            all(h[y] == y for h in stabilizer) for y in range(n)
        )
        answer *= fixed_points
    return answer


def total_class_count(n, verbose=False):
    total = Fraction(0)
    for parts in partitions(n):
        q, cycles = canonical_permutation(parts)
        centralizer_size = 1
        multiplicities = {}
        for length in parts:
            multiplicities[length] = multiplicities.get(length, 0) + 1
        for length, count in multiplicities.items():
            centralizer_size *= (length ** count) * factorial(count)

        fixed_sum = 0
        seen = 0
        for g in centralizer_elements(cycles, n):
            fixed_sum += equivariant_endomorphism_count(q, g)
            seen += 1
        assert seen == centralizer_size
        contribution = Fraction(fixed_sum, centralizer_size)
        assert contribution.denominator == 1
        total += contribution
        if verbose:
            print(parts, int(contribution), flush=True)
    assert total.denominator == 1
    return int(total)


def connected_from_totals(totals):
    """Inverse Euler transform: A(x)=prod_k (1-x^k)^(-C[k])."""
    max_n = len(totals) - 1
    connected = [0] * (max_n + 1)
    # Recurrence n*A_n = sum_{k=1}^n b_k*A_{n-k},
    # where b_k = sum_{d|k} d*C_d.
    for n in range(1, max_n + 1):
        b_n = n * totals[n]
        for k in range(1, n):
            b_k = sum(d * connected[d] for d in range(1, k + 1) if k % d == 0)
            b_n -= b_k * totals[n - k]
        prior = sum(d * connected[d] for d in range(1, n) if n % d == 0)
        assert (b_n - prior) % n == 0
        connected[n] = (b_n - prior) // n
    return connected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("max_n", type=int, nargs="?", default=7)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    totals = [1]
    for n in range(1, args.max_n + 1):
        value = total_class_count(n, args.verbose)
        totals.append(value)
        print(f"A[{n}]={value}", flush=True)
    connected = connected_from_totals(totals)
    print("all:", totals)
    print("connected:", connected)


if __name__ == "__main__":
    main()
